apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vlc2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vlc2
    app.kubernetes.io/part-of: tkrw-pr712-0075-0057-app
  name: devfile-sample-vlc2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vlc2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vlc2
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0057-tenant/tkrw-pr712-0075-0057-app/devfile-sample-vlc2@sha256:72ec3b6b24747d73913d14d533b75e978bbed80abdb048364dbf1043d6a08332
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
